### PR TITLE
Element: removed redundant code in attr(), fix #1

### LINKED ISSUE #1: Element.php: redundant code in attr()
The lines https://github.com/k-next/html/blob/master/src/Html/Element.php#L246-L248 in `src/html/Element.php` seem to be redundant and never reached if you consider the first lines of the method (https://github.com/k-next/html/blob/master/src/Html/Element.php#L237-L242).

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by distantnative** [comment]
Weird result, since still 100% of Element.php is covered by tests

**Comment by bastianallgeier** [comment]
Hm I don't understand it either. Maybe some internal weighing changed. Should we still merge it anyway?

**Comment by distantnative** [comment]
I'd say yes, since it really does not affect the actual quality of tests coverage.

**Comment by bastianallgeier** [comment]
Done :)

**Pull request merged**
